language: node_js
dist: trusty
sudo: false

node_js:
  - '10.3.0'

branches:
   only:
      - master

before_script:
  - npm install -g @angular/cli
  - npm install

script:
  - npm run build:demo:prod

cache:
  directories:
    - ./node_modules/

deploy:
  local-dir: 'dist/pioneer-tree'
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
