import { PioneerTreeService, IPioneerTreeService } from "../services/pioneer-tree.service"
import { IPioneerTreeRepeater, PioneerTreeRepeater } from "./pioneer-tree-repeater.model"

export interface IPioneerTreeNode {
    /**
     * Get UID of node
     * Generated by model at init
     */
    getId(): string;


    /**
     * Get collection of content classes to set on ngClass
     */
    getContentClasses(): string[];

    /**
     * A repeater lives inside a node
     * this is the node id
     */
    pioneerTreeRepeater: IPioneerTreeRepeater;
}

export class PioneerTreeNode implements IPioneerTreeNode {

    pioneerTreeRepeater: IPioneerTreeRepeater;

    private uid: string;

    constructor(private pioneerTreeService: IPioneerTreeService) {
        this.generateUid();
        this.pioneerTreeRepeater = new PioneerTreeRepeater()
    }

    getId(): string {
        return this.uid
    }

    getContentClasses(): string[] {
        const classes = [] as string[]

        if (this.pioneerTreeService.currentSelectedNodeId === this.getId()) {
            classes.push('pt-node-selected')
        }

        return classes;
    }

    private generateUid(): void {
        this.uid = 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function (c) {
            var r = Math.random() * 16 | 0, v = c == 'x' ? r : (r & 0x3 | 0x8);
            return v.toString(16);
        });
    }
}