import { PioneerTreeService, IPioneerTreeService } from "../services/pioneer-tree.service"
import { IPioneerTreeRepeater, PioneerTreeRepeater } from "./pioneer-tree-repeater.model"

export interface IPioneerTreeNode {
    /**
     * Get UID of node
     * Generated by model at init
     */
    getId(): string;

    /**
     * A repeater lives inside a node
     * this is the node id
     */
    pioneerTreeRepeater: IPioneerTreeRepeater;
}

export class PioneerTreeNode implements IPioneerTreeNode {
    pioneerTreeRepeater: IPioneerTreeRepeater;

    private uid: string;

    constructor() {
        this.generateUid();
        this.pioneerTreeRepeater = new PioneerTreeRepeater()
    }

    getId(): string {
        return this.uid
    }

    private generateUid(): void {
        this.uid = 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function (c) {
            var r = Math.random() * 16 | 0, v = c == 'x' ? r : (r & 0x3 | 0x8);
            return v.toString(16);
        });
    }
}