export interface IPioneerTreeNode {
    /**
     * Get UID of node
     * Generated by model at init
     */
    getId(): string;

    /**
     * Node was clicked
     */
    isSelected: boolean;
}

export class PioneerTreeNode implements IPioneerTreeNode {
    isSelected = false;
    private uid: string;

    constructor() {
         this.generateUid();
    }

    getId(): string {
        return this.uid
    }

    private generateUid(): void {
        this.uid = 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function (c) {
            var r = Math.random() * 16 | 0, v = c == 'x' ? r : (r & 0x3 | 0x8);
            return v.toString(16);
        });
    }
}